import createClient from "openapi-fetch";
import type { paths, components } from "./apischema"; // generated by openapi-typescript
export type SimplePollingEvent = components["schemas"]["EventItem"];

const client = createClient<paths>({ baseUrl: "http://localhost:4000" });

export const loadEventsGenerated = async () => {
  const { data, error } = await client.GET("/api/events", { params: { query: { limit: 10 } } });
  if (error) {
    throw new Error(JSON.stringify(error));
  }
  return data?.items;
};
