openapi: 3.0.0
info:
  title: Event Management API
  version: 1.0.0
  description: API for managing events and their details.
paths:
  /api/events:
    get:
      summary: Get all events
      description: Retrieve a list of all events.
      tags:
        - Events
      parameters: # Add parameters here
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Maximum number of events to return
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                  - items
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/EventItem'
        '500':
          description: Internal server error

    post:
      summary: Create a new event
      description: Add a new event to the system.
      tags:
        - Events
      requestBody:
        description: Event object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventItemInput'
      responses:
        '200':
          description: Successful operation
        '500':
          description: Internal server error

  /api/events/{id}:
    get:
      summary: Get event by ID
      description: Retrieve a specific event by its ID.
      tags:
        - Events
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the event to retrieve
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventItem'
        '404':
          description: Event not found
        '500':
          description: Internal server error

components:
  schemas:
    RecordEntry:
      type: object
      properties:
        name:
          type: string
          description: Name of the participant.
        answer:
          type: string
          enum:
            - yes
            - no
            - if-needed
          description: Participant's answer.
    EventDate:
      type: object
      properties:
        timestamp:
          type: integer
          description: Timestamp of the date.
        records:
          type: array
          items:
            $ref: '#/components/schemas/RecordEntry'
          description: Records for this date.
    EventItem:
      type: object
      required:
        - title
        - dates
        - id
      properties:
        id:
          type: integer
          description: Unique identifier for the event.
        location:
          type: string
          description: Location of the event.
        title:
          type: string
          description: Title of the event.
        dates:
          type: array
          items:
            $ref: '#/components/schemas/EventDate'
          description: Dates and associated records for the event.
    EventItemInput:
      type: object
      required:
        - title
        - dates
      properties:
        location:
          type: string
          description: Location of the event.
        title:
          type: string
          description: Title of the event.
        dates:
          type: array
          items:
            $ref: '#/components/schemas/EventDate'
          description: Dates and associated records for the event.
